#page title
page_title                                : SpeakAI - Learn Language Anytime and Anywhere                # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6447890228            # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                    # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/cn/app/speakai/id6447890228     # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=cc.edream.speak                                          # Enter Google Play Store URL.
presskit_download_link                    : https://edreamai.feishu.cn/docx/C5OGd008Hoz6tVxKfygcdIIRnsA                    # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : SpeakAI - Learn Language                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Chat with the most advanced AI tutor in the world, receive real-time feedback, and help you learn a new language.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : edream,Inc        
your_link                                 : https://edream.cc                     
# your_city                                 : Canton                                
email_address                             : service@edream.cc
# facebook_username                         :                                           
# instagram_username                        : ebaehr
# twitter_username                          : ebaehr
github_username                           : https://github.com/edreamai/edreamai.github.io
# youtube_username                          :
# mastodon_link                             : https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : AI Tutor powered by OpenAI
    description                           : Anytime, anywhere, your personal spoken language teacher
    fontawesome_icon_name                 : magic
  
  - title                                 : Multiple Languages Learning
    description                           : Now we support Chinese, English, Japanese, Korean, French, German, Italian, and Spanish
    fontawesome_icon_name                 : language

  - title                                 : Scenario Courses
    description                           : Scenario courses allow you to easily deal with dialogues in various occasions
    fontawesome_icon_name                 : book
    
  - title                                 : Grammar Correction
    description                           : Real-time feedback, providing grammar suggestions
    fontawesome_icon_name                 : mobile

  - title                                 : Real-time Mode
    description                           : Real-time dialogue, immersive experience
    fontawesome_icon_name                 : graduation-cap

  - title                                 : Rich Voice
    description                           : 100+ voice to choose from, always one option fit for you
    fontawesome_icon_name                 : microphone


# Theme Settings
topbar_color                              : "#f3f3f3"
topbar_transparency                       : 1
topbar_title_color                        : "#000"

# cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#f3f3f3"
cover_overlay_transparency                : 1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#f3f3f3"

link_color                                : "#1d63ea"

app_title_color                           : "#000"
app_price_color                           : "#000"
app_description_color                     : "#000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
