#page title
page_title                                : SpeakAI - 随时随地学习口语               # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6447890228            # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                    # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/cn/app/speakai/id6447890228     # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=cc.edream.speak                                          # Enter Google Play Store URL.
presskit_download_link                    : https://edreamai.feishu.cn/docx/C5OGd008Hoz6tVxKfygcdIIRnsA                    # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : SpeakAI - 口语学习                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : 免费                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : 通过我们的AI助手，沉浸式学习体验，多语言学习，支持中文、英文、日文、韩文、法文、德文、意大利文和西班牙文。情境课程，轻松应对各种对话场景，实时语法纠错，丰富的语音选择。从今天开始你的语言学习之旅吧！

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : edream,Inc        
your_link                                 : https://edream.cc                     
# your_city                                 : Canton                                
email_address                             : service@edream.cc
# facebook_username                         :                                           
# instagram_username                        : ebaehr
# twitter_username                          : ebaehr
github_username                           : https://github.com/edreamai/edreamai.github.io
# youtube_username                          :
# mastodon_link                             : https://mastodon.social/@ebaehr



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : 智能AI导师
    description                           : 我们的应用采用先进的AI技术，提供智能AI助手，为您的语言学习之旅提供指导。享受个性化学习路径和互动练习，根据您的需求和节奏进行调整。
    fontawesome_icon_name                 : magic
  
  - title                                 : 多语言学习
    description                           : 我们支持中文、英文、日文、韩文、法文、德文、意大利文和西班牙文等多种语言。轻松探索不同文化，扩展您的全球交流能力。
    fontawesome_icon_name                 : language

  - title                                 : 情景课程
    description                           : 我们的应用提供基于情境的课程，帮助您掌握各种真实场景中的对话和交流。学会应对日常对话、商务交流、旅行经历等各种情境。
    fontawesome_icon_name                 : book
    
  - title                                 : 实时语法纠错
    description                           : 实时获得反馈和个性化的语法建议，提升语言水平。我们的应用帮助您发现并纠正语法错误，确保您的口语表达准确流利。
    fontawesome_icon_name                 : mobile

  - title                                 : 实时对话模式
    description                           : 通过我们的实时对话功能，沉浸式地体验真实的语言学习。与虚拟伙伴和母语者进行对话，提高发音和流利度，动态互动，让语言焕发生机。
    fontawesome_icon_name                 : graduation-cap

  - title                                 : 丰富的语音选择
    description                           : 我们提供100多种语音选择，让您为语言学习之旅找到完美的配音。用与你共鸣的声音学习，让语言生动起来。
    fontawesome_icon_name                 : microphone


# Theme Settings
topbar_color                              : "#f3f3f3"
topbar_transparency                       : 1
topbar_title_color                        : "#000"

# cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#f3f3f3"
cover_overlay_transparency                : 1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#f3f3f3"

link_color                                : "#1d63ea"

app_title_color                           : "#000"
app_price_color                           : "#000"
app_description_color                     : "#000"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
